dietobaza/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('nutriLink.urls')),
    path('admin/', admin.site.urls),
    path("nutriLink/", include("nutriLink.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nutriLink/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from .forms import LoginForm
from django.contrib import admin

from . import views

app_name = 'nutriLink'

urlpatterns = [
    path("", views.index, name="index"),

    # path("contact/", views.contact, name="contact"),
    path('signup/', views.signup, name="signup"),
path('login/', auth_views.LoginView.as_view(template_name='nutriLink/login.html', authentication_form=LoginForm), name='login'),
    path('new/', views.new_recipe, name="new_recipe"),
    path('<int:pk>/', views.recipe, name="recipe"),
<<<<<<< Updated upstream
    path('profile/', views.profile, name="user")
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
=======

    path('profile/', views.profile, name="user"),

    path('recipe_text/<int:pk>/', views.recipe_text, name="recipe_text")

]
>>>>>>> Stashed changes

nutriLink/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.contrib.auth.models import User

class Recipe(models.Model):
    recipe_name = models.CharField(max_length=150, unique=True)
    user = models.ForeignKey(User, related_name='recipes', on_delete=models.CASCADE)
    contents = models.TextField()
    picture = models.ImageField(upload_to='uploads/')
    pub_date = models.DateTimeField(auto_now_add=True)
    tag = models.CharField(max_length=100, default='')

    def __str__(self):
        return self.recipe_name

class Ingredient(models.Model):
    name = models.CharField(max_length=30, unique=True)
    kcal = models.IntegerField()
    amount = models.IntegerField()
    unit = models.CharField(max_length=20)

    def __str__(self):
        return self.name

class Review(models.Model):
    user = models.ForeignKey(User, related_name='created_reviews', on_delete=models.CASCADE)
    recipe = models.ForeignKey(Recipe, related_name='recipe_reviews', on_delete=models.CASCADE)
    stars = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    comment = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)

class RecipeIngredient(models.Model):
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    amount = models.IntegerField()
    other_measure = models.CharField(max_length=100, blank=True, null=True)

class Diet(models.Model):
    diet_name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.diet_name

class Exclusion(models.Model):
    diet = models.ForeignKey(Diet, on_delete=models.CASCADE)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    max_amount = models.IntegerField()

    def __str__(self):
        return self.ingredient.name

nutriLink/forms.py
from django import forms
from datetime import datetime
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import Recipe, Review

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    username = forms.CharField(widget=forms.TextInput(attrs={
        "placeholder": "Twoja nazwa użytkownika",
        "class": 'w-full py-4 px-6 rounded-xl'
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        "placeholder": "Twój e-mail",
        "class": 'w-full py-4 px-6 rounded-xl'
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        "placeholder": "Twoje hasło",
        "class": 'w-full py-4 px-6 rounded-xl'
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        "placeholder": "Powtórz hasło",
        "class": 'w-full py-4 px-6 rounded-xl'
    }))

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        "placeholder": "Nazwa użytkownika",
        "class": 'w-full py-4 px-6 rounded-xl',
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Hasło',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class NewRecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ('recipe_name', 'contents', 'picture', 'tag')

        widgets = {
            'recipe_name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'contents': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            # 'picture': forms.FileInput(attrs={
            #     'class': INPUT_CLASSES
            # })
            'tag': forms.TextInput(attrs={
                'placeholder': 'dieta',
                'class': INPUT_CLASSES
            }),
        }
        labels = {
            'recipe_name': "Nazwa przepisu",
            'contents': "Treść",
            'picture': "Zdjęcie",
            'tag': "Tag (dieta)",
        }

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('stars', 'comment')
        widgets = {
                'stars': forms.NumberInput(attrs={
                'class': INPUT_CLASSES
            }),
                'comment': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            })
        }
        labels = {
            'stars': "Gwiazdki",
            'comment': "Komentarz"
        }

nutriLink/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from nutriLink.forms import SignupForm, LoginForm, NewRecipeForm, ReviewForm
from nutriLink.models import Recipe, Diet, Review, Exclusion
from django.core.paginator import Paginator


def index(request):
    diets = Diet.objects.all()
    query = request.GET.get('dietlist', '')

    if not query=="":
        recipes = Recipe.objects.filter(Q(tag__icontains=query) | Q(contents__icontains=query))
    else:
        recipes = Recipe.objects.all()

    page_q = request.GET.get('page_q', '3')
    paginator = Paginator(recipes, page_q)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    if request.method == 'POST':
        logout(request)
        del request.session['user_id']
        return redirect('nutriLink/')

    return render(request, 'nutriLink/index.html',{
        'recipes': recipes,
        'diets': diets,
        'query': query,
        'page_obj': page_obj,
        'page': page_number,
    })

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('/nutriLink/login/')

    else:
        form = SignupForm()

    return render(request, 'nutriLink/signup.html',{
        'form': form
    })

def recipe(request, pk):
    recipe = get_object_or_404(Recipe, pk=pk)
    reviews = Review.objects.filter(recipe=recipe)

    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.recipe = recipe
            review.user = request.user
            review.save()
            return redirect('nutriLink:recipe', pk=pk)
    else:
        form = ReviewForm()

    try:
        return render(request, 'nutriLink/recipe.html', {
            'recipe': recipe,
            'reviews': reviews,
            'form': form,
        })
    except (KeyError, Recipe.DoesNotExist):
        return render(request,"nutriLink/recipe.html",{
                'recipe': recipe,
                'error_message': "Przepis nie istnieje.",
                'reviews': reviews,
            },
        )

@login_required
def new_recipe(request):
    if request.method == 'POST':
        form = NewRecipeForm(request.POST, request.FILES)
        if form.is_valid():
            recipe = form.save(commit=False)
            recipe.user = request.user
            recipe.save()

            return redirect('nutriLink:recipe', pk=recipe.id)
    else:
        form = NewRecipeForm()

    return render(request, 'nutriLink/recipe_form.html', {
        'form': form,
        'title': 'Dodaj przepis',
    })

@login_required
def profile(request):
    recipes = Recipe.objects.filter(user=request.user)

    return render(request, 'nutriLink/user.html', {
        'recipes': recipes,
    })

def recipe_text(request, pk):
    response = HttpResponse(content_type='text/plain')
    response['Content-Disposition'] = 'attachment; filename=Recipe.txt'
    q = Recipe.objects.get(id=pk)
    ingredients = q.recipe_name
    response.writelines(ingredients)
    response.writelines("\n\n")
    ingredients = q.contents
    response.writelines(ingredients)
    return response

templates/nutriLink/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src ="https://cdn.tailwindcss.com"></script>
{#    <link rel="stylesheet" href="font-awesome-4.7.0/css/font-awesome.min.css">#}
    <title>{% block title %}{% endblock %} | nutriLink</title>
    <style>
        .fade-out {
            opacity: 0;
            transform: translateY(25%);
            transition: opacity 1s ease-out;
        }
        .fade-in {
            opacity: 0;
            transform: translateY(-98%);
            transition: opacity 1s ease-in-out, transform 1s ease-in-out;
        }
    </style>
</head>
<body>

<nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200 bg-blue-100">
    <a href="/nutriLink" class="text-xl font-semibold">nutriLink</a>

    <div class="space-x-6" id="top">
    
            {% if request.user.is_authenticated %}
                <div class="grid grid-cols-3 justify-items-center">
                <a href="{% url 'nutriLink:new_recipe' %}" class="px-3 py-3 text-lg font-semibold hover:text-gray-500">Dodaj przepis</a>
{#                <a href="{% url 'nutriLink:user' %}" class="px-3 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700"><i class="fa fa-user-circle" aria-hidden="true"></i></a>#}
                <a href="{% url 'nutriLink:user' %}" class="px-3 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Mój profil</a>
                <form method="post" action="{% url 'nutriLink:logout' %}">
                {% csrf_token %}
                <button type="submit" class="px-3 py-3 text-lg bg-gray-500 text-white rounded-xl hover:bg-gray-700">Wyloguj</button>
                </form>
                </div>
            {% else %}
                <div class="grid grid-cols-2 justify-items-center">
                <a href="{% url 'nutriLink:signup' %}" class="px-3 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Zarejestruj się</a>
                <a href="{% url 'nutriLink:login' %}" class="px-3 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Zaloguj się</a>
                </div>
            {% endif %}
        
    </div>
</nav>
<div class="px-6 py-6">
    {% block content %}
    {% endblock %}
</div>

<footer class="py-6 px-6 flex justify-between bg-gray-800">
    <div class="w-2/3 pr-10">
        <h3 class="mb-5 font-semibold text-gray-400">O nas</h3>

        <p class="text-lg text-gray-500">Informacje</p>
    </div>

    <div class="w-1/3">
        <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

        <ul class="space-y-2">
            <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">O nas</a></li>
            <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Polityka prywatności</a></li>
            <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Warunki użytkowania</a></li>

        </ul>
    </div>
</footer>
    <script>
        // JavaScript to trigger the fade-in animation
        document.addEventListener('DOMContentLoaded', function() {
            var animatedDiv = document.getElementById('top');
            animatedDiv.classList.add('fade-in');
            // Delay the animation start slightly for effect
            setTimeout(function() {
                animatedDiv.style.opacity = '1';
                animatedDiv.style.transform = 'translateX(0)';
            }, 300);
        });
    </script>
</script>
</body>
</html>

templates/nutriLink/index.html
{% extends 'nutriLink/base.html' %}

{% block title %} Strona główna {% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-6 bg-gray-100 rounded-xl flex justify-center">

        <div class="grid grid-cols-2 gap-3">
            <div class="grid grid-cols-2 gap-3">
                <select name="dietlist" form="filter" class="py-2 px-2 rounded-xl">
                    <option value="">--wybierz dietę--</option>
                    {% for diet in diets %}
                        <option value="{{ diet.diet_name }}" {% if diet.diet_name == query %} selected {% endif %}>
                            {{ diet.diet_name }}
                        </option>
                    {% endfor %}
                </select>
                <form method="get" action="{% url 'nutriLink:index' %}" id="filter">
                    <button class="mt-2 py-4 px-8 text-lg bg-gray-500 text-white rounded-xl">Filtruj</button>
                </form>
            </div>

            <div class="grid gap-3 justify-end place-content-center">
                <form method="get" action="{% url 'nutriLink:index' %}" id="paginator">
                    <input type="number" name="page_q" value="{{ page_q }}" placeholder="3" min="1" class="mt-2 py-1 px-3 w-1/5">
                    <button class="mt-2 py-2 px-6 text-sm bg-gray-300  rounded-xl">Wybierz liczbę obiektów na stronie</button>
                </form>
            </div>

        </div>
    </div>
    
    <div class="mt-6 px-6 py-6 bg-blue-50 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Przepisy</h2>
            
        <div class="grid grid-cols-3 gap-3">
            {% for item in page_obj %}
                <div>
                    <a href="{% url 'nutriLink:recipe' item.id %}">
                        <div class="p-6 bg-white rounded-t-xl">
                            <h2 class="text-2xl font-semibold">{{ item.recipe_name }}</h2>
                        </div>
                        <div>
                            <img src="{{ item.picture.url }}" class="rounded-xl" width="500px">
                        </div>
                    </a>
                </div>
          {% endfor %}
        </div>
    
        <div class="pagination">
            <span class="step-links">
            <p class="text-sm">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}">Poprzednia strona <<</a>
                {% else %}
                    <a>Poprzednia strona <<</a>
                {% endif %}

                {% for i in page_obj.paginator.page_range %}
                    {% if page_obj.number == i %}
                    <a href="#">{{ i }} </a>
                    {% else %}
                    <a href="?page={{ i }}">{{ i }}</a>
                    {% endif %}
                {% endfor %}

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">>> Następna strona</a>
                {% else %}
                    <a>>> Następna strona</a>
                {% endif %}
            </p>
            </span>
        </div>
    </div>

{% endblock %}

templates/nutriLink/ingredients_form.html
{% extends 'nutriLink/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}

<h1 class="mb-6 text-3xl">{{ title }}</h1>

<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}

    <div class="space-y-4">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
    {% endif %}

    <button class="mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Dodaj</button>
</form>
<br>
    <a href={% url 'nutriLink:index' %}><u>Powrót do strony głównej</u></a>

{% endblock %}

templates/nutriLink/login.html
{% extends 'nutriLink/base.html' %}

{% block title %}Log In{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Log In</h1>

    <form method="post" action='.'>
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}

            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}

templates/nutriLink/recipe.html
{% extends 'nutriLink/base.html' %}

{% block title %} {{ recipe.recipe_name }} {% endblock %}

{% block content %}

    <div class="grid grid-cols-5 gap-6">

        <div class="col-span-3 p-6 bg-gray-100 rounded-xl">
            <h1 class="mb-6 text-3xl">{{ recipe.recipe_name }}</h1>
            <p class="text-gray-500 text-xs"><strong>Autor: </strong>{{ recipe.user.username }}</p>
            <p class="text-gray-400 text-xs"><strong>Opublikowano: </strong>{{ recipe.pub_date }}</p>
{#            <br>#}
            <p class="text-gray-400 text-xs"><strong>Dieta: </strong>{{ recipe.tag }}</p>
            <br>
            <p style="white-space: pre-line;">{{ recipe.contents }}</p>
        </div>

        <div class="col-span-2">
            <img src="{{ recipe.picture.url }}" class="rounded-xl">
        </div>

        <a href="{% url 'nutriLink:recipe_text' recipe.id %}">
            <button class="mt-2 py-2 px-4 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white" id="download">Pobierz przepis</button>
        </a>
        <div id="message-container"></div>
        {% if not form.errors and not form.non_field_errors %}
                <script>
                    document.getElementById('download').addEventListener('click', function(event) {

                        var messageContainer = document.getElementById('message-container');

                        // Clear any existing messages
                        messageContainer.innerHTML = '';

                        // Create the message element
                        var message = document.createElement('div');
                        message.className = "mt-2 p-6 py-2 px-2 ml-auto text-lg bg-green-700 hover:bg-teal-700 rounded-xl text-white";
                        message.innerText = 'Gratulujemy świetnego wyboru!';

                        // Add the message to the container
                        messageContainer.appendChild(message);

                        // Fade out the message after 5 seconds
                        setTimeout(function() {
                            message.classList.add('fade-out');
                            setTimeout(function() {
                                message.style.display = 'none';
                            }, 1000); // Matches the duration of the CSS transition
                        }, 5000); // Start fading out after 5 seconds
                    });
                </script>
            {% endif %}

    </div>

    <div class="mt-6 px-6 py-6 bg-gray-100 rounded-xl">
        <h3 class="mb-12 text-xl text-center font-semibold">Oceny</h3>

        <div class="grid grid-cols-3 gap-3">
            {% for comment in reviews %}
                <div>
                        <div class="p-6 bg-white rounded-xl">
                            <h2 class="text-base italic">{{ comment.user }}:</h2>
                            <br>
                            <h2 class="text-base">Ocena: {{ comment.stars }}</h2>
                            
                            <h2 class="text-base">Komentarz: {{ comment.comment }}</h2>
                            <br>
                            <h3 class="text-sm">{{ comment.pub_date }}</h3>
                        </div>
                    </a>
                </div>
            {% endfor %}

        </div>
    
        <div class="mt-6 px-6 py-6">
        
            {% if request.user.is_authenticated %}
                <h3 class="mb-12 text-l font-semibold">Oceń przepis</h3> 
                <form method="post" action=".">
                    {% csrf_token %}
                    <div class="space-y-4">
                        {{ form.as_p }}
                    </div>

                    {% if form.errors or form.non_field_errors %}
                        <div class="mb-3 p-6 bg-red-100 rounded-xl">
                            {% for field in form %}
                                {{ field.errors }}
                            {% endfor %}
    
                            {{ form.non_field_errors }}
                        </div>
                    {% endif %}
                
                    <button class="mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white" id="opinion-button">Publikuj</button>
                </form>

            {% else %}
                <a href="{% url 'nutriLink:login' %}" class="px-3 py-3 text-lg font-semibold bg-gray-400 text-white rounded-xl hover:bg-gray-500">Zaloguj się, aby ocenić przepis</a>
            {% endif %}
        </div>
    </div>

{% endblock %}

templates/nutriLink/recipe_form.html
{% extends 'nutriLink/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}

<h1 class="mb-6 text-3xl">{{ title }}</h1>

<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}

    <div class="space-y-4">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
    {% endif %}

    <button class="mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Dodaj</button>
</form>
<br>
    <a href={% url 'nutriLink:index' %}><u>Return to main page</u></a>

{% endblock %}

templates/nutriLink/redirect.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    value = {{ value }}
</head>
<body>
    <meta http-equiv="refresh" content="0; URL={% url "nutriLink:user" value %}">
</body>
</html>

templates/nutriLink/signup.html
{% extends 'nutriLink/base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">E-mail</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Confirm password</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}

            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}

templates/nutriLink/user.html
{% extends 'nutriLink/base.html' %}

{% block title %} Profil {% endblock %}

{% block content %}
    
    <div class="mt-6 px-6 py-6 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Moje przepisy</h2>

        <div class="grid grid-cols-3 gap-3">
{#            {% if recipes.exists %}#}
{#                <h2 class="mb-12 font-semibold text-2xl text-center">Nie masz jeszcze żadnych przepisów!</h2>#}
{#            {% endif %}#}
            {% for item in recipes %}
                <div>
                    <a href="{% url 'nutriLink:recipe' item.id %}">
                        <div class="p-6 bg-white rounded-t-xl">
                            <h2 class="text-2xl">{{ item.recipe_name }}</h2>
                        </div>
                        <div>
                            <img src="{{ item.picture.url }}" class="rounded-t-xl" width="500px">
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}